###Obtener todas las categorías
GET http://localhost:3000/api/categories

### Obtener productos por categoría y precio máximo
GET http://localhost:3000/api/products?category=audio&maxPrice=100

### Obtener producto por id
GET http://localhost:3000/api/products/2

###Obtener todos los productos
GET http://localhost:3000/api/products?offset=30&limit=20

### Obtener items del carrito de un usuario
GET http://localhost:3000/api/cart/1

### Agregar un producto al carrito
POST http://localhost:3000/api/cart/1
Content-Type: application/json

{
  "productId": 7,
  "quantity": 3
}

### Actualizar la cantidad de un producto en el carrito
PATCH http://localhost:3000/api/cart/1
Content-Type: application/json

{
  "productId": 2,
  "quantity": -5
}

### Eliminar un producto del carrito
DELETE http://localhost:3000/api/cart/1
Content-Type: application/json

{
  "productId": 4
}

### Eliminar todos los productos del carrito
DELETE http://localhost:3000/api/cart/1/all

### Login de usuario
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}

### Registro de usuario
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "username": "newuser2",
  "password": "newpassword1"
}

### Logout de usuario
POST http://localhost:3000/api/user/logout

### Ruta protegida
GET http://localhost:3000/protected