###Obtener todas las categorías
GET https://ecommerce-qhiw.onrender.com/api/categories

### Obtener productos por categoría y precio máximo
GET https://ecommerce-qhiw.onrender.com/api/products?limit=100

### Obtener producto por id
GET https://ecommerce-qhiw.onrender.com/api/products/2

###Obtener todos los productos
GET https://ecommerce-qhiw.onrender.com/api/products?offset=30&limit=20

### Obtener items del carrito de un usuario
GET https://ecommerce-qhiw.onrender.com/api/cart/21

### Agregar un producto al carrito
POST https://ecommerce-qhiw.onrender.com/api/cart/21
Content-Type: application/json

{
  "productId": 7,
  "quantity": 1
}

### Actualizar la cantidad de un producto en el carrito
PATCH https://ecommerce-qhiw.onrender.com/api/cart/1
Content-Type: application/json

{
  "productId": 2,
  "quantity": -5
}

### Eliminar un producto del carrito
DELETE https://ecommerce-qhiw.onrender.com/api/cart/1
Content-Type: application/json

{
  "productId": 4
}

### Eliminar todos los productos del carrito
DELETE https://ecommerce-qhiw.onrender.com/api/cart/1/all

### Login de usuario
POST https://ecommerce-qhiw.onrender.com/api/user/login
Content-Type: application/json

{
  "username": "newuser2",
  "password": "newpassword1"
}

### Registro de usuario
POST https://ecommerce-qhiw.onrender.com/api/user/register
Content-Type: application/json

{
  "username": "newuser2",
  "password": "newpassword1"
}

### Logout de usuario
POST https://ecommerce-qhiw.onrender.com/api/user/logout

### Ruta protegida
GET https://ecommerce-qhiw.onrender.com/protected